#This is a Compose File
version: '3.9'
services:
    web:
        build: 
            context: .
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        
        restart: on-failure    
networks:
    hostnet: {}        

